version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemp.yaml --s3-bucket p1-codepipeline --output-template-file 
      - aws cloudformation package --template-file frontTemplate.yml --s3-bucket p1-codepipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemp.yml
    - frontTemplate.yml
    - outputSamTemplate.yaml
